name:           NGLess
version:        '0.0.0'
category:       Domain Specific Language
author:         Luis Pedro Coelho and others (see AUTHORS)
maintainer:     luis@luispedro.org
license:        MIT
license-file:   COPYING
c-sources:
  - NGLess/Dependencies/embedded.c
  - NGLess/Data/FastQ.c
default-extensions:
  - BangPatterns
  - OverloadedStrings
  - LambdaCase
  - TupleSections
other-extensions:
  - DeriveDataTypeable
  - TemplateHaskell
dependencies:
  - aeson >=0.9
  - ansi-terminal
  - async
  - atomic-write >=0.2
  - base
  - bytestring
  - bytestring-lexing
  - optparse-applicative
  - conduit
  - conduit-algorithms >=0.0.3.0
  - conduit-extra >=1.1.12
  - conduit-combinators
  - configurator
  - containers
  - convertible
  - data-default
  - deepseq >=1.3
  - directory
  - edit-distance >=0.2
  - either
  - errors >=2.1
  - extra >=1.4
  - filemanip >=0.3.6
  - filepath >=1.3
  - file-embed >=0.0.8
  - gitrev
  - hashable
  - hashtables
  - http-conduit
  - http-client
  - IntervalMap >=0.5
  - monad-control
  - mtl >=2.2
  - MissingH >=1.3
  - network
  - parsec >=3.1
  - primitive >=0.6
  - process >=1.2.3
  - old-locale
  - random
  - safe
  - safeio >=0.0.2
  - strict
  - stm
  - stm-chans
  - stm-conduit >=2.7
  - resourcet >=1.1
  - tar >=0.5
  - template-haskell
  - text >=1.2
  - time >=1.5
  - transformers
  - transformers-base
  - vector >=0.11
  - vector-algorithms
  - yaml
  - zlib

executables:
  ngless:
    main: Main.hs
    source-dirs: NGLess/
    when:
    - condition: impl(ghc >=8.0)
      then:
        ghc-options:
        - -Wall
        - -fwarn-tabs
        - -fno-warn-missing-signatures
        - -threaded
        - -O2
        - -rtsopts
        - ! '"-with-rtsopts=-A64m -n4m -H"'
      else:
        ghc-options:
        - -Wall
        - -fwarn-tabs
        - -fno-warn-missing-signatures
        - -threaded
        - -O2
        - -rtsopts
        - ! '"-with-rtsopts=-A64m -n4m -H -qg"'
    - condition: os(windows)
      cpp-options: -DWINDOWS
    - condition: ! '!(os(windows))'
      dependencies:
      - bzlib-conduit
      - double-conversion
      - unix
    - condition: ! '!(flag(embed))'
      then:
        cc-options: -DNO_EMBED_SAMTOOLS_BWA
        cpp-options: -DNO_EMBED_SAMTOOLS_BWA
      else:
        ld-options:
        - -static
        - -pthread
tests:
  nglesstest:
    main: Tests.hs
    source-dirs: NGLess/
    cpp-options: -DIS_BUILDING_TEST
    dependencies:
    - HUnit >=1.3
    - test-framework >=0.8
    - test-framework-hunit
    - test-framework-quickcheck2
    - test-framework-th
    - QuickCheck >=2.8
    when:
    - condition: impl(ghc >=8.0)
      then:
        ghc-options:
        - -Wall
        - -fwarn-tabs
        - -fno-warn-missing-signatures
        - -threaded
        - -O2
        - -rtsopts
        - ! '"-with-rtsopts=-A64m -n4m -H"'
      else:
        ghc-options:
        - -Wall
        - -fwarn-tabs
        - -fno-warn-missing-signatures
        - -threaded
        - -O2
        - -rtsopts
        - ! '"-with-rtsopts=-A64m -n4m -H -qg"'
    - condition: os(windows)
      cpp-options: -DWINDOWS
    - condition: ! '!(os(windows))'
      dependencies:
      - bzlib-conduit
      - double-conversion
      - unix
    - condition: ! '!(flag(embed))'
      then:
        cc-options: -DNO_EMBED_SAMTOOLS_BWA
        cpp-options: -DNO_EMBED_SAMTOOLS_BWA
      else:
        ld-options:
        - -static
        - -pthread
benchmarks:
  nglessbench:
    main: Bench.hs
    source-dirs: NGLess/
    dependencies:
    - HUnit >=1.3
    - criterion
    when:
    - condition: impl(ghc >=8.0)
      then:
        ghc-options:
        - -Wall
        - -fwarn-tabs
        - -fno-warn-missing-signatures
        - -threaded
        - -O2
        - -rtsopts
        - ! '"-with-rtsopts=-A64m -n4m -H"'
      else:
        ghc-options:
        - -Wall
        - -fwarn-tabs
        - -fno-warn-missing-signatures
        - -threaded
        - -O2
        - -rtsopts
        - ! '"-with-rtsopts=-A64m -n4m -H -qg"'
    - condition: os(windows)
      cpp-options: -DWINDOWS
    - condition: ! '!(os(windows))'
      dependencies:
      - bzlib-conduit
      - double-conversion
      - unix
    - condition: ! '!(flag(embed))'
      then:
        cc-options: -DNO_EMBED_SAMTOOLS_BWA
        cpp-options: -DNO_EMBED_SAMTOOLS_BWA
      else:
        ld-options:
        - -static
        - -pthread
flags:
  embed:
    description: Embed bwa/samtools
    manual: false
    default: false
